(()=>{'use strict';let credential='',cursor='',timer;
const by=id=>document.getElementById(id), text=(tag,value,cls)=>{const n=document.createElement(tag);n.textContent=String(value).slice(0,512);if(cls)n.className=cls;return n};
async function get(path){const r=await fetch(path,{method:'GET',headers:{Authorization:'Bearer '+credential,Accept:'application/json'},cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer'});if(!r.ok)throw new Error(r.status===401?'unauthorized':'request failed');return r.json()}
const oneOf=(v,a)=>a.includes(v), connect=['online','stale','offline'], sessions=['absent','starting','idle','working','steering','interrupting','stopped','failed','projection_unavailable'], turns=['none','active','terminal_unknown'], activities=['idle','command','file_change','web_search','connected_tool','other'], kinds=['ship.online','ship.stale','ship.offline','ship.snapshot','persona.installed','persona.removed','session.state','turn.state','activity','agent.message','approval.waiting','request.refused','projection.warning'];
function validSnapshot(s){return s&&s.schema_version===1&&Array.isArray(s.ships)&&s.ships.every(x=>oneOf(x.connectivity,connect)&&Array.isArray(x.personas)&&x.personas.every(p=>oneOf(p.session,sessions)&&oneOf(p.turn,turns)&&oneOf(p.activity,activities)))}
function validate(v){if(v.schema_version!==1)throw new Error('unsupported schema');if(v.ships&&!validSnapshot(v))throw new Error('invalid fleet response');if(v.snapshot&&!validSnapshot(v.snapshot))throw new Error('invalid fleet response');if(v.events&&(!Array.isArray(v.events)||!v.events.every(e=>e.schema_version===1&&oneOf(e.kind,kinds))))throw new Error('invalid fleet response');if(v.events&&(!Number.isSafeInteger(v.next_cursor)||v.next_cursor<0))throw new Error('invalid fleet response');return v}
function render(snapshot){const root=by('ships');root.replaceChildren();for(const s of snapshot.ships||[]){const card=text('article','', 'ship');card.append(text('h2',s.ship_label||s.ship_id));card.append(text('p',s.connectivity,'status '+s.connectivity));const t=document.createElement('table'),head=document.createElement('tr');for(const h of ['Persona','Session','Turn','Activity','Notice'])head.append(text('th',h));t.append(head);for(const p of s.personas||[]){const tr=document.createElement('tr');for(const [label,v] of [['Persona',p.persona],['Session',p.session],['Turn',p.turn],['Activity',p.activity],['Notice',p.approval_waiting?'Local approval waiting':'—']]){const td=text('td',v);td.dataset.label=label;tr.append(td)}t.append(tr)}card.append(t);if(s.truncated)card.append(text('p',`${s.omitted_persona_count} personas omitted`));root.append(card)}}
function addEvents(events){const out=by('events');for(const e of events||[]){out.prepend(text('li',`${e.cursor} · ${e.ship_id} · ${e.persona||'ship'} · ${e.kind}`));while(out.children.length>200)out.lastChild.remove()}}
async function poll(){try{const q=cursor?'?after='+encodeURIComponent(cursor)+'&limit=100':'?limit=100',r=validate(await get('/api/fleet/v1/events/stream'+q));if(r.gap){by('boundary').textContent=`Gap: ${r.gap.reason}. State was refreshed.`;by('events').replaceChildren()}if(r.snapshot)render(r.snapshot);addEvents(r.events);const epoch=r.snapshot?r.snapshot.fleet_epoch:r.gap?r.gap.current_epoch:(r.events||[])[0]?.fleet_epoch:cursor.split(':')[0];if(!epoch)throw new Error('invalid fleet response');cursor=`${epoch}:${r.next_cursor}`;timer=setTimeout(poll,1000)}catch(e){by('error').textContent=e.message;timer=setTimeout(poll,2000)}}
by('auth').addEventListener('submit',async e=>{e.preventDefault();clearTimeout(timer);credential=by('credential').value;by('credential').value='';try{const s=validate(await get('/api/fleet/v1/snapshot'));by('fleet').hidden=false;by('auth').hidden=true;render(s);cursor=`${s.fleet_epoch}:${s.snapshot_cursor}`;poll()}catch(x){credential='';by('error').textContent=x.message}})
})();
