//go:build linux && amd64 && !shipmates_qualifier_payload

package installer

import "embed"

// Generated by tools/generate-installer-payloads.sh. These are the only
// executable bytes the amd64 installer may publish.
//
//go:embed payloads/linux_amd64/shipmates-m3-qualifier-run payloads/linux_amd64/shipmates-cgroup-launcher
var targetPayloads embed.FS

const payloadArch = "linux_amd64"
