//go:build linux && arm64 && !shipmates_qualifier_payload

package installer

import "embed"

// Generated by tools/generate-installer-payloads.sh.
//
//go:embed payloads/linux_arm64/shipmates-m3-qualifier-run payloads/linux_arm64/shipmates-cgroup-launcher
var targetPayloads embed.FS

const payloadArch = "linux_arm64"
